/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'dealer-organizations': DealerOrganization;
    'audit-logs': AuditLog;
    media: Media;
    brands: Brand;
    'vehicle-models': VehicleModel;
    generations: Generation;
    trims: Trim;
    'specification-definitions': SpecificationDefinition;
    'trim-specifications': TrimSpecification;
    'dealer-locations': DealerLocation;
    'dealer-brands': DealerBrand;
    offers: Offer;
    'price-history': PriceHistory;
    'availability-snapshots': AvailabilitySnapshot;
    promotions: Promotion;
    'warranty-terms': WarrantyTerm;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'dealer-organizations': DealerOrganizationsSelect<false> | DealerOrganizationsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'vehicle-models': VehicleModelsSelect<false> | VehicleModelsSelect<true>;
    generations: GenerationsSelect<false> | GenerationsSelect<true>;
    trims: TrimsSelect<false> | TrimsSelect<true>;
    'specification-definitions': SpecificationDefinitionsSelect<false> | SpecificationDefinitionsSelect<true>;
    'trim-specifications': TrimSpecificationsSelect<false> | TrimSpecificationsSelect<true>;
    'dealer-locations': DealerLocationsSelect<false> | DealerLocationsSelect<true>;
    'dealer-brands': DealerBrandsSelect<false> | DealerBrandsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'price-history': PriceHistorySelect<false> | PriceHistorySelect<true>;
    'availability-snapshots': AvailabilitySnapshotsSelect<false> | AvailabilitySnapshotsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'warranty-terms': WarrantyTermsSelect<false> | WarrantyTermsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'data_editor' | 'dealer_manager' | 'dealer_agent';
  dealerOrganization?: (number | null) | DealerOrganization;
  status: 'active' | 'suspended';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-organizations".
 */
export interface DealerOrganization {
  id: number;
  name: string;
  legalName?: string | null;
  slug: string;
  website?: string | null;
  phone?: string | null;
  email?: string | null;
  description?: string | null;
  status: 'active' | 'suspended';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actorId?: string | null;
  actorEmail?: string | null;
  actorRole?: ('admin' | 'data_editor' | 'dealer_manager' | 'dealer_agent') | null;
  dealerOrganizationId?: string | null;
  action: 'create' | 'update' | 'delete';
  targetCollection: string;
  targetDocumentId: string;
  changedFields?:
    | {
        field: string;
        id?: string | null;
      }[]
    | null;
  occurredAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  kind: 'brand-logo' | 'vehicle' | 'interior' | 'technical' | 'other';
  sourceUrl?: string | null;
  attribution?: string | null;
  licenseNote?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  countryOfOrigin?: string | null;
  website?: string | null;
  logo?: (number | null) | Media;
  description?: string | null;
  catalogStatus: 'draft' | 'in_review' | 'published' | 'rejected';
  sourceType?: ('manufacturer' | 'official-dealer' | 'regulatory' | 'manual-verification' | 'other') | null;
  /**
   * URL, document reference, brochure reference or other traceable source.
   */
  sourceReference?: string | null;
  sourceObservedAt?: string | null;
  /**
   * Internal provenance notes; never part of the public catalog projection.
   */
  sourceNotes?: string | null;
  qualityFlags?:
    | {
        code: string;
        severity: 'warning' | 'blocking';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewNotes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-models".
 */
export interface VehicleModel {
  id: number;
  brand: number | Brand;
  name: string;
  slug: string;
  identityKey: string;
  modelCode?: string | null;
  heroImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  description?: string | null;
  catalogStatus: 'draft' | 'in_review' | 'published' | 'rejected';
  sourceType?: ('manufacturer' | 'official-dealer' | 'regulatory' | 'manual-verification' | 'other') | null;
  /**
   * URL, document reference, brochure reference or other traceable source.
   */
  sourceReference?: string | null;
  sourceObservedAt?: string | null;
  /**
   * Internal provenance notes; never part of the public catalog projection.
   */
  sourceNotes?: string | null;
  qualityFlags?:
    | {
        code: string;
        severity: 'warning' | 'blocking';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewNotes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generations".
 */
export interface Generation {
  id: number;
  model: number | VehicleModel;
  name: string;
  slug: string;
  identityKey: string;
  generationCode?: string | null;
  productionStartYear?: number | null;
  productionEndYear?: number | null;
  gallery?: (number | Media)[] | null;
  notes?: string | null;
  catalogStatus: 'draft' | 'in_review' | 'published' | 'rejected';
  sourceType?: ('manufacturer' | 'official-dealer' | 'regulatory' | 'manual-verification' | 'other') | null;
  /**
   * URL, document reference, brochure reference or other traceable source.
   */
  sourceReference?: string | null;
  sourceObservedAt?: string | null;
  /**
   * Internal provenance notes; never part of the public catalog projection.
   */
  sourceNotes?: string | null;
  qualityFlags?:
    | {
        code: string;
        severity: 'warning' | 'blocking';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewNotes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trims".
 */
export interface Trim {
  id: number;
  generation: number | Generation;
  name: string;
  slug: string;
  identityKey: string;
  modelYearStart?: number | null;
  modelYearEnd?: number | null;
  bodyStyle?:
    | (
        | 'city-car'
        | 'hatchback'
        | 'sedan'
        | 'wagon'
        | 'suv'
        | 'crossover'
        | 'pickup'
        | 'van-mpv'
        | 'coupe'
        | 'convertible'
        | 'commercial'
        | 'other'
      )
    | null;
  fuelType?: ('petrol' | 'diesel' | 'hybrid' | 'plug-in-hybrid' | 'electric' | 'lpg' | 'other') | null;
  transmission?: ('manual' | 'automatic' | 'cvt' | 'dct' | 'automated-manual' | 'single-speed' | 'other') | null;
  driveType?: ('fwd' | 'rwd' | 'awd' | '4wd' | 'other') | null;
  seats?: number | null;
  doors?: number | null;
  gallery?: (number | Media)[] | null;
  notes?: string | null;
  catalogStatus: 'draft' | 'in_review' | 'published' | 'rejected';
  sourceType?: ('manufacturer' | 'official-dealer' | 'regulatory' | 'manual-verification' | 'other') | null;
  /**
   * URL, document reference, brochure reference or other traceable source.
   */
  sourceReference?: string | null;
  sourceObservedAt?: string | null;
  /**
   * Internal provenance notes; never part of the public catalog projection.
   */
  sourceNotes?: string | null;
  qualityFlags?:
    | {
        code: string;
        severity: 'warning' | 'blocking';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewNotes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specification-definitions".
 */
export interface SpecificationDefinition {
  id: number;
  key: string;
  label: string;
  category:
    | 'engine'
    | 'electric-system'
    | 'performance'
    | 'drivetrain'
    | 'dimensions'
    | 'capacity'
    | 'efficiency'
    | 'chassis'
    | 'safety'
    | 'comfort'
    | 'other';
  valueType: 'number' | 'text' | 'boolean' | 'option';
  unit?:
    | (
        | 'mm'
        | 'cm'
        | 'm'
        | 'l'
        | 'cm3'
        | 'kw'
        | 'hp'
        | 'nm'
        | 'kg'
        | 'km-h'
        | 'l-100km'
        | 'kwh-100km'
        | 'km'
        | 'g-km'
        | 's'
        | 'percent'
      )
    | null;
  allowedOptions?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  comparable?: boolean | null;
  filterable?: boolean | null;
  sortOrder?: number | null;
  description?: string | null;
  catalogStatus: 'draft' | 'in_review' | 'published' | 'rejected';
  sourceType?: ('manufacturer' | 'official-dealer' | 'regulatory' | 'manual-verification' | 'other') | null;
  /**
   * URL, document reference, brochure reference or other traceable source.
   */
  sourceReference?: string | null;
  sourceObservedAt?: string | null;
  /**
   * Internal provenance notes; never part of the public catalog projection.
   */
  sourceNotes?: string | null;
  qualityFlags?:
    | {
        code: string;
        severity: 'warning' | 'blocking';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewNotes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trim-specifications".
 */
export interface TrimSpecification {
  id: number;
  trim: number | Trim;
  definition: number | SpecificationDefinition;
  identityKey: string;
  valueStatus: 'known' | 'unknown' | 'not-applicable';
  numberValue?: number | null;
  textValue?: string | null;
  booleanValue?: ('true' | 'false') | null;
  optionValue?: string | null;
  sourceNote?: string | null;
  catalogStatus: 'draft' | 'in_review' | 'published' | 'rejected';
  sourceType?: ('manufacturer' | 'official-dealer' | 'regulatory' | 'manual-verification' | 'other') | null;
  /**
   * URL, document reference, brochure reference or other traceable source.
   */
  sourceReference?: string | null;
  sourceObservedAt?: string | null;
  /**
   * Internal provenance notes; never part of the public catalog projection.
   */
  sourceNotes?: string | null;
  qualityFlags?:
    | {
        code: string;
        severity: 'warning' | 'blocking';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  reviewNotes?: string | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-locations".
 */
export interface DealerLocation {
  id: number;
  dealerOrganization: number | DealerOrganization;
  name: string;
  slug: string;
  identityKey: string;
  city: string;
  address: string;
  phone?: string | null;
  email?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-brands".
 */
export interface DealerBrand {
  id: number;
  dealerOrganization: number | DealerOrganization;
  brand: number | Brand;
  identityKey: string;
  status: 'active' | 'inactive';
  officialSince?: string | null;
  sourceReference: string;
  observedAt: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  dealerOrganization: number | DealerOrganization;
  location?: (number | null) | DealerLocation;
  trim: number | Trim;
  headline: string;
  externalReference?: string | null;
  status: 'active' | 'inactive' | 'archived';
  sourceReference: string;
  observedAt: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-history".
 */
export interface PriceHistory {
  id: number;
  dealerOrganization: number | DealerOrganization;
  offer: number | Offer;
  amount: number;
  currency: 'XAF';
  priceType: 'list' | 'from' | 'promotional';
  observedAt: string;
  sourceReference: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability-snapshots".
 */
export interface AvailabilitySnapshot {
  id: number;
  dealerOrganization: number | DealerOrganization;
  offer: number | Offer;
  availability: 'in_stock' | 'limited' | 'order_only' | 'out_of_stock' | 'unknown';
  quantity?: number | null;
  observedAt: string;
  sourceReference: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  dealerOrganization: number | DealerOrganization;
  offer: number | Offer;
  title: string;
  description?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  status: 'draft' | 'active' | 'expired';
  sourceReference: string;
  observedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranty-terms".
 */
export interface WarrantyTerm {
  id: number;
  dealerOrganization: number | DealerOrganization;
  offer: number | Offer;
  months?: number | null;
  distanceKm?: number | null;
  coverage: string;
  status: 'active' | 'inactive';
  sourceReference: string;
  observedAt: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'dealer-organizations';
        value: number | DealerOrganization;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'vehicle-models';
        value: number | VehicleModel;
      } | null)
    | ({
        relationTo: 'generations';
        value: number | Generation;
      } | null)
    | ({
        relationTo: 'trims';
        value: number | Trim;
      } | null)
    | ({
        relationTo: 'specification-definitions';
        value: number | SpecificationDefinition;
      } | null)
    | ({
        relationTo: 'trim-specifications';
        value: number | TrimSpecification;
      } | null)
    | ({
        relationTo: 'dealer-locations';
        value: number | DealerLocation;
      } | null)
    | ({
        relationTo: 'dealer-brands';
        value: number | DealerBrand;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'price-history';
        value: number | PriceHistory;
      } | null)
    | ({
        relationTo: 'availability-snapshots';
        value: number | AvailabilitySnapshot;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'warranty-terms';
        value: number | WarrantyTerm;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  dealerOrganization?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-organizations_select".
 */
export interface DealerOrganizationsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  slug?: T;
  website?: T;
  phone?: T;
  email?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actorId?: T;
  actorEmail?: T;
  actorRole?: T;
  dealerOrganizationId?: T;
  action?: T;
  targetCollection?: T;
  targetDocumentId?: T;
  changedFields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  occurredAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  kind?: T;
  sourceUrl?: T;
  attribution?: T;
  licenseNote?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  countryOfOrigin?: T;
  website?: T;
  logo?: T;
  description?: T;
  catalogStatus?: T;
  sourceType?: T;
  sourceReference?: T;
  sourceObservedAt?: T;
  sourceNotes?: T;
  qualityFlags?:
    | T
    | {
        code?: T;
        severity?: T;
        note?: T;
        id?: T;
      };
  reviewNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicle-models_select".
 */
export interface VehicleModelsSelect<T extends boolean = true> {
  brand?: T;
  name?: T;
  slug?: T;
  identityKey?: T;
  modelCode?: T;
  heroImage?: T;
  gallery?: T;
  description?: T;
  catalogStatus?: T;
  sourceType?: T;
  sourceReference?: T;
  sourceObservedAt?: T;
  sourceNotes?: T;
  qualityFlags?:
    | T
    | {
        code?: T;
        severity?: T;
        note?: T;
        id?: T;
      };
  reviewNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generations_select".
 */
export interface GenerationsSelect<T extends boolean = true> {
  model?: T;
  name?: T;
  slug?: T;
  identityKey?: T;
  generationCode?: T;
  productionStartYear?: T;
  productionEndYear?: T;
  gallery?: T;
  notes?: T;
  catalogStatus?: T;
  sourceType?: T;
  sourceReference?: T;
  sourceObservedAt?: T;
  sourceNotes?: T;
  qualityFlags?:
    | T
    | {
        code?: T;
        severity?: T;
        note?: T;
        id?: T;
      };
  reviewNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trims_select".
 */
export interface TrimsSelect<T extends boolean = true> {
  generation?: T;
  name?: T;
  slug?: T;
  identityKey?: T;
  modelYearStart?: T;
  modelYearEnd?: T;
  bodyStyle?: T;
  fuelType?: T;
  transmission?: T;
  driveType?: T;
  seats?: T;
  doors?: T;
  gallery?: T;
  notes?: T;
  catalogStatus?: T;
  sourceType?: T;
  sourceReference?: T;
  sourceObservedAt?: T;
  sourceNotes?: T;
  qualityFlags?:
    | T
    | {
        code?: T;
        severity?: T;
        note?: T;
        id?: T;
      };
  reviewNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specification-definitions_select".
 */
export interface SpecificationDefinitionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  category?: T;
  valueType?: T;
  unit?: T;
  allowedOptions?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  comparable?: T;
  filterable?: T;
  sortOrder?: T;
  description?: T;
  catalogStatus?: T;
  sourceType?: T;
  sourceReference?: T;
  sourceObservedAt?: T;
  sourceNotes?: T;
  qualityFlags?:
    | T
    | {
        code?: T;
        severity?: T;
        note?: T;
        id?: T;
      };
  reviewNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trim-specifications_select".
 */
export interface TrimSpecificationsSelect<T extends boolean = true> {
  trim?: T;
  definition?: T;
  identityKey?: T;
  valueStatus?: T;
  numberValue?: T;
  textValue?: T;
  booleanValue?: T;
  optionValue?: T;
  sourceNote?: T;
  catalogStatus?: T;
  sourceType?: T;
  sourceReference?: T;
  sourceObservedAt?: T;
  sourceNotes?: T;
  qualityFlags?:
    | T
    | {
        code?: T;
        severity?: T;
        note?: T;
        id?: T;
      };
  reviewNotes?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-locations_select".
 */
export interface DealerLocationsSelect<T extends boolean = true> {
  dealerOrganization?: T;
  name?: T;
  slug?: T;
  identityKey?: T;
  city?: T;
  address?: T;
  phone?: T;
  email?: T;
  latitude?: T;
  longitude?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-brands_select".
 */
export interface DealerBrandsSelect<T extends boolean = true> {
  dealerOrganization?: T;
  brand?: T;
  identityKey?: T;
  status?: T;
  officialSince?: T;
  sourceReference?: T;
  observedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  dealerOrganization?: T;
  location?: T;
  trim?: T;
  headline?: T;
  externalReference?: T;
  status?: T;
  sourceReference?: T;
  observedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-history_select".
 */
export interface PriceHistorySelect<T extends boolean = true> {
  dealerOrganization?: T;
  offer?: T;
  amount?: T;
  currency?: T;
  priceType?: T;
  observedAt?: T;
  sourceReference?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability-snapshots_select".
 */
export interface AvailabilitySnapshotsSelect<T extends boolean = true> {
  dealerOrganization?: T;
  offer?: T;
  availability?: T;
  quantity?: T;
  observedAt?: T;
  sourceReference?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  dealerOrganization?: T;
  offer?: T;
  title?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  status?: T;
  sourceReference?: T;
  observedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranty-terms_select".
 */
export interface WarrantyTermsSelect<T extends boolean = true> {
  dealerOrganization?: T;
  offer?: T;
  months?: T;
  distanceKm?: T;
  coverage?: T;
  status?: T;
  sourceReference?: T;
  observedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}